name: Development pipes

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create Docker image
        run: docker build -t ${{ github.repository }}:${{ github.sha }} .

  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.26
      - name: Install dependencies
        run: bun install
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-deps-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-deps-

  lint:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-deps-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-deps-
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.26
      - name: Lint project
        run: bun lint

  build:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-deps-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-deps-

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.26

      - name: Build project
        run: bun compile

      - name: Upload dist directory
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
